export { authController } from './authController'
export { userController } from './userController'
export { mediaController } from './mediaController'
export { chatController } from './chatController'
export { webinarController } from './webinarController'
export { medicamentController } from './medicamentController'